### ISSUE TITLE
License is not specified

### ISSUE THREAD

**Issue by asashour** [wylieconlon/lsp-editor-adapter#27]
Hi,

Thanks for developing this, the idea is great.

However, please specify a license, so users can expect what to get when they use the library.

**Comment by krassowski** [comment]
According to package.json file it is ISC licence.

**Comment by wylieconlon** [comment]
Yes, I was happy to go with the ISC license in the package.json but it's not clear outside of this. Will clarify.

**Comment by asashour** [comment]
I see, thanks for Info, but I guess it wouldn't harm to add `LICENSE.txt` to the project.

**Comment by asashour** [comment]
Thanks.
